### ISSUE TITLE
run real git commands instead of hitting the API

### ISSUE THREAD

**Issue by Gummibeer** [Astrotomic/opendor.me#120]
https://stackoverflow.com/questions/9597410/list-all-developers-on-a-project-in-git/36325643

https://github.com/albertz/helpers/blob/master/git-log-remote.sh

https://stackoverflow.com/a/24750310/4907524

**Comment by bhushan** [comment]
@Gummibeer what are you trying to achieve exactly? Show list of contributors on page somewhere ?

**Comment by Gummibeer** [comment]
replaced by #125 as it solves more issues with fewer problems to solve.
