### ISSUE TITLE
Setting environment variables to write in Github Setup in README

### ISSUE THREAD

**Issue by fumiya5863** [Astrotomic/opendor.me#121]
**Describe**
I get a 404 when I try to use Sign-in using OAuth on Github in a local development environment.

<img width="1265" alt="スクリーンショット 2021-07-26 15 56 57" src="https://user-images.githubusercontent.com/60251958/126946006-b0c58658-9567-42e8-82a8-1ee3079b654a.png">

**cause**
Is the environment variable setting in the .env.example file described in the Github Setup section of the README wrong?

Environment variable settings in the README(Screenshots)
<img width="852" alt="スクリーンショット 2021-07-26 16 07 50" src="https://user-images.githubusercontent.com/60251958/126947291-27798144-e22a-48b7-81c6-ad62b21ddf49.png">

Environment variable settings in the .env.example file(Screenshots)
<img width="587" alt="スクリーンショット 2021-07-26 16 08 12" src="https://user-images.githubusercontent.com/60251958/126947383-7b23bca9-ca90-4b88-83c7-e49a80c7ab6a.png">

As mentioned above, isn't the content to be written in the README to write the environment variable settings for .env.example?

**Comment by bhushan** [comment]
@pushpak1300
