### ISSUE TITLE
All contributions not shown on profile

### ISSUE THREAD

**Issue by adevade** [Astrotomic/opendor.me#48]
When I view my contributions page or profile page, I can't see all repositories I've contributed to.

**Example:**
View a repo I've committed to: https://github.com/ploi-deploy/ploi-translations/graphs/contributors
View my profile on opendor.me: https://opendor.me/@adevade
It's not included on my profile.

If I'm not mistaken, I expect it to show all repos I've contributed to? Both small and big contributions.

Or does it only show repos from users that are also connected to opendor.me?
If that's the case, maybe add some information about it in the FAQ?

**Comment by Gummibeer** [comment]
Hey,

thanks for reaching out - it's this one:
> Or does it only show repos from users that are also connected to opendor.me?

It's based on GitHub API limitations. So for @NathanGeerinck would be the one who has to sign-up as he's the only public member of ploi-deploy.

There's already a draft for that - I will work on it.
https://github.com/Astrotomic/opendor.me/blob/dev/content/faqs/why-are-contributions-missing.md

In case you have other questions or things that should be clarified in FAQs: you can also PR them. 🙂
