### ISSUE TITLE
Flex truncate is a bad combination

### ISSUE THREAD

**Issue by Gummibeer** [Astrotomic/opendor.me#61]
On some elements throughout the app I use the `truncate` class - but this doesn't work if the truncated element is a direct child of a flexbox one.
This isn't a heavy bug but a bit annoying to see overflows.

@aidan-casey has already proposed two general solutions - so in case anyone fixes this, please author Aidan as well.
You can use https://github-author.astrotomic.info to find the required git author line by username.
https://play.tailwindcss.com/7kUHkqwVLS
https://play.tailwindcss.com/q2o1zT466U

**Screenshots**
<img width="319" alt="Bildschirmfoto 2021-04-19 um 12 37 12" src="https://user-images.githubusercontent.com/6187884/115223331-f8740f80-a10b-11eb-9582-40d26a74256e.png">

**Comment by aidan-casey** [comment]
@Gummibeer - Can you point me to where that screenshot is on the actual site? Not recognizing the card.

**Comment by aidan-casey** [comment]
See #64
