### ISSUE TITLE
Slow profile loading speed

### ISSUE THREAD

**Issue by Gummibeer** [Astrotomic/opendor.me#77]
The Microsoft profile page is too slow. Even the spatie one was slow already but acceptable. But Microsoft takes multiple seconds to load.
We have to find a solution to keep the page loading speed consistent independent of repository count.

There are two heavy things:
1) DB queries, primary the `contributions` (user) or `repositories` (organization) are slow.
2) rendering - it takes "years" to render several hundred repository components.

The query isn't that bad yet - so I would focus on the blade part. There should be some kind of pagination. The current approach on the user profile seems good - show 6 repos and have a "show more/all" button. There should be an info like "showing 12 of 258 repositories".
But the current user profile still renders all entries Serverside but hides them.
This has to be changed to a client rendered version and API.

Another idea would be to offload this to Algolia. Show 6 by default and have a search bar - with autosuggestion (?).

The members of an organization face the same problem - microsoft has ~4500 public members ...
I think that we could remove that list and instead link to a prefilled advanced user search. We could do the same for contributors.

https://opendor.me/@microsoft

**Comment by aidan-casey** [comment]
@Gummibeer - How about lazy loading the repos as you go down the screen? I would think with that many repos you _might_ want a search, but since part of the point of opendor.me is the "wow factor" involved in seeing all the contributions, it would make sense to be able to show them all as you scroll down.

**Comment by Gummibeer** [comment]
On the organization profile the load on scroll would work. But on the user profile we have several vendors so loading all contributions by each vendor would mean that I can't reach the second vendor until the first one is fully loaded.
As I'm generally not a so big fan of endless scrollers and would prefer a consistent experience I would like to trigger loading more entries by a button click.
I'm sure that with alpine.js this isn't too much work as we push new entries to the component property and everything else updates itself.
It's a partly urgent task - we don't hit any timeouts yet but for sure it's a bad user experience.

I will have to check the Nova replacement first and merge it. As soon as that's done I would take a look on this one except anyone already started working on it.

**Comment by Gummibeer** [comment]
The largest profile is 46MB of HTML right now, takes 1min to transfer and render and makes it nearly impossible to interact with the page - on desktop, I won't try it on mobile.

So the endless scroller idea is off the table as it won't solve that issue (in case someone scrolls doooooooown). My absolute favorite would be a button triggered multiple-page floating pagination.

What I mean is a pagination rendering 12 (TBD) elements per page and starts with page 1. The user clicks "load more" and it loads second page but appends that to the first page (so renders 24 elements). The user now clicks again "load more" and same happens for page 3 (36 elements). Now the user clicks again and it loads and appends page 4 but also removes page 1 from rendered elements (but possibly keep the data in memory(?). So the user now has a "load more" button at the end and a "load previous" button on top of the list.
That way we will never render more than 3 pages but the user doesn't have to decide between page 1 or 2. The biggest challenge could be to keep the relative scroll position while removing page 1. 🤔 I'm not such a JS expert but the viewport should stay sticky while removing and appending pages so the user can easily continue to read thee next eentries.

**Comment by aidan-casey** [comment]
I guess I'm still not sure why endless scrolling is off the table. It actually seems to fit this use case perfectly while providing a better user experience. Take a look at Facebook or Instagram, where they offset the scroll bar once the next "page" is loaded. This keeps a user from just sticking to the bottom of the page and scrolling forever. This way if I want to see previous pages, I just scroll up.

**Comment by Gummibeer** [comment]
So far I know Facebook & Instagram & Twitter use some kind of shadow DOM or whatever to prevent MBs of HTML from blocking the browser. So they "disable" some HTML that is far out of viewport but keep its spacing for the scrollbar. I'm not sure if a simple CSS `visibility: hidden` solves that!? 🤔
But if we would just load 46MB of HTML in the browser it's not important if that was done in one go or incrementally - it's just too much for most/(all?) browsers. That's why I thought about really removing the pages - in case a simple CSS thing would also do it GREAT! But I don't want to introduce a crazy shadow DOM JS library thing just for performant pagination.

**Comment by aidan-casey** [comment]
It looks like Facebook makes a GraphQL request (that returns some pre-rendered object representing html) when the scroll bar hits the bottom of the page. It then displays this on the page and maintains the scroll bar offset. Because the current scroll position is higher than the end of the page after the new content is loaded, it doesn't continue to load.

You already have AlpineJS as a dependency, so I think this could be achieved with relative ease utilizing that and an API endpoint. You could use one of these [methods](https://stackoverflow.com/questions/63233506/refreshing-data-after-the-fact-in-alpinejs) to append new data to an object based on a JSON response from an API and have that function called when the scroll bar reaches the end of the section.

**Comment by poldixd** [comment]
You can try `content-visibility: auto` for better browser rendering performance: [content-visibility: the new CSS property that boosts your rendering performance](https://web.dev/content-visibility/)

**Comment by aidan-casey** [comment]
@poldixd - Except for the fact that its [browser support](https://caniuse.com/mdn-css_properties_content-visibility) is pretty much limited to Chromium.

**Comment by Gummibeer** [comment]
But the underlying `contain` attribute is officiall.
https://developer.mozilla.org/en-US/docs/Web/CSS/contain

And the real `visibility` could be changed by JS in case it helps with performance.
