### ISSUE TITLE
Add registered_at timestamp to users

### ISSUE THREAD

**Issue by Gummibeer** [Astrotomic/opendor.me#84]
As we create users before they register we need another column to indicate when they've registered.
That column should be anonymized when needed and filled during first sign-in. In best case the core registered event is also fired.

**Comment by fumiya5863** [comment]
I don't know if I'm understanding this.

When a user is created, timestamps will be registered as shown below, but do you mean to create a separate column for registered_at?

https://github.com/Astrotomic/opendor.me/blob/7447542ab3fd06677a17c7da0bec23c8dd7a844b/database/migrations/2014_10_12_000000_create_users_table.php#L23

Also, are you referring to the date and time when the GitHub account was created?

**Comment by Gummibeer** [comment]
Hey,
yes, we need an additional `registered_at` column. Users can be created in the background from GitHub API but aren't registered yet.

**Comment by fumiya5863** [comment]
Understood.

I came to the conclusion that the registered_at column should contain the date and time when the GitHub account was created.

If this is correct, I will take care of this issue.

If I'm wrong, please let me know.

**Comment by Gummibeer** [comment]
No, it should be the time when the user first clicked "sign in" on the opendor.me website.
I'm not that sure for existing users. 🤔
Leaving it blank for them would mean that the column is filled when they log in next. The closer date should be to copy the `created_at` value for already registered users (these are only a subset of all user records).

**Comment by fumiya5863** [comment]
I see.

The created_at when the user is registered in the DB is the time after the user has been created, so you can get the timestamps at the moment the "sign in" button is pressed and store them in the registered_at.
