### ISSUE TITLE
Fix Twitter OG card

### ISSUE THREAD

**Issue by Gummibeer** [Astrotomic/opendor.me#90]
https://cards-dev.twitter.com/validator

**Comment by codedge** [comment]
Could be solved in #88. 
The only tag left, that the validator complains about, is `twitter:text:title`. Worth extending your [php-open-graph](https://github.com/Astrotomic/php-open-graph) package?

**Comment by Gummibeer** [comment]
https://github.com/Astrotomic/opendor.me/commit/058e70006c5907e9957fc952fbb7f75ba4a79bc1
